CREATE TABLE Stocks(
ID_FRUIT SERIAL PRIMARY KEY,
FRUIT VARCHAR(25)NOT NULL,
QUANTITY FLOAT NOT NULL
);

Create TABLE Purchased(
ID SERIAL PRIMARY KEY,
ID_FRUIT INTEGER NOT NULL,
FRUIT VARCHAR(25) NOT NULL,
QUANTITY FLOAT NOT NULL,
PRICE_FOR_KG FLOAT NOT NULL,
DATE_OF_INPUT DATE DEFAULT current_date,
FOREIGN KEY (ID_FRUIT) REFERENCES Stocks(ID_FRUIT)
);

Create TABLE Sales(
ID SERIAL PRIMARY KEY,
ID_FRUIT INTEGER NOT NULL,
FRUIT VARCHAR(25) NOT NULL,
QUANTITY FLOAT NOT NULL,
PRICE_FOR_KG FLOAT NOT NULL,
DATE_OF_INPUT DATE DEFAULT current_date,
FOREIGN KEY (ID_FRUIT) REFERENCES Stocks(ID_FRUIT)
);
